# Johnatan Meño

In [1]:
import numpy as np 
import pandas as pd

In [2]:
from scipy.stats import norm

## Cargando datos

## Datos de entrenamiento

# Datos x no anomalos

In [3]:
data_x_normales = pd.read_excel('estaturas.xlsx','normales')

In [4]:
data_x_normales

Estatura  Edad
0       1.77    26
1       1.74    31
2       1.72    24
3       1.78    40
4       1.65    32
5       1.66    35
6       1.64    25
7       1.85    34
8       1.85    26
9       1.75    21
10      1.73    23
11      1.79    28
12      1.82    24
13      1.65    25
14      1.79    25
15      1.72    34
16      1.70    26
17      1.57    25
18      1.66    26
19      1.75    27

## Datos de Validación 

## Data x anomalos

In [5]:
data_x_anomalias = pd.read_excel('estaturas.xlsx','anomalias')

In [6]:
data_x_anomalias

Estatura   Edad
0      0.25    2.4
1    175.10    2.5
2      0.15  250.0
3    150.00   14.0

## Convrtiendo a matrices

In [7]:
x_normales = data_x_normales.values

In [8]:
x_normales.shape

(20, 2)

In [9]:
x_anomalias = data_x_anomalias.values

In [10]:
x_anomalias.shape

(4, 2)

# Etiqueta de las anomalias

In [11]:
y_anomalias = np.array ([[1],
                         [1],
                         [1],
                         [1],])                       

In [12]:
y_anomalias

array([[1],
       [1],
       [1],
       [1]])

##

## Calcuando medias

In [13]:
medias = np.mean(x_normales, axis=0)

In [14]:
medias

array([ 1.7295, 27.85  ])

## Calculando varianzas

In [15]:
varianza = np.var(x_normales, axis=0)

In [16]:
varianza

array([5.32475e-03, 2.24275e+01])

In [17]:
## generando archivo de excel para ir guardando los resultados 
import xlwt
from xlwt import Workbook 
wb = Workbook() 
sheet1 = wb.add_sheet('Sheet 1', cell_overwrite_ok=True)

In [18]:
## poniendo nombres en columnas
sheet1.write(0, 1, 'Cadena de configuración') 
sheet1.write(0, 2, 'f1Score')

In [19]:
from sklearn.metrics import f1_score

## Funcion de clasificacion

In [20]:
def clasificacion(x,media,varianza,epsilon,y):
    ## probablididad conjunta
    prob  = (norm.pdf(x[:,0],media[0],varianza[0]))**(norm.pdf(x[:,1],media[1],varianza[1]))
                         
    ## evaluando la condicional para epsilon
    condicional = (prob < epsilon)
    
    ## ahora calculo las metricas
    F1_Validation = f1_score(y, condicional)
    
    ## cadena de configuracion
    cadena_config = "Clasificaciòn con""_Epsilon="+str(epsilon)
    
    print("f1score",F1_Validation*100, "%")
    print("Anomalo = 1:",condicional*1)
    
    return cadena_config, F1_Validation 

In [21]:
cad0,f0, = clasificacion(x_anomalias,medias,varianza,0.10,y_anomalias)

f1score 100.0 %
Anomalo = 1: [1 1 1 1]


In [22]:
##LLenado con valores la fila 1
sheet1.write(1, 1, cad0) 
sheet1.write(1, 2, f0) 

In [23]:
cad1,f1, = clasificacion(x_anomalias,medias,varianza,0.09,y_anomalias)

f1score 100.0 %
Anomalo = 1: [1 1 1 1]


In [24]:
##LLenado con valores la fila 1
sheet1.write(2, 1, cad1) 
sheet1.write(2, 2, f1) 

In [25]:
cad2,f2, = clasificacion(x_anomalias,medias,varianza,0.000000000000000000000000000000000000000000001,y_anomalias)

f1score 100.0 %
Anomalo = 1: [1 1 1 1]


In [26]:
##LLenado con valores la fila 1
sheet1.write(3, 1, cad2) 
sheet1.write(3, 2, f2) 

In [27]:
## escribiendo el archivo de excel al disco duro
## escribiendo el archivo de excel al disco duro
## escribiendo el archivo de excel al disco duro
## escribiendo el archivo de excel al disco duro
## escribiendo el archivo de excel al disco duro
## escribiendo el archivo de excel al disco duro
## escribiendo el archivo de excel al disco duro
wb.save('Resumen.xls')

# Función para datos de prueba

In [64]:
def clasificacion_p(x1,x2):
    ## probablididad conjunta
    prob  = (norm.pdf(x1,medias[0],varianza[0]))**(norm.pdf(x2,medias[1],varianza[1]))
                                               
    ## evaluando la condicional para epsilon
    if prob < 0.000000000000000000000000000000000000000000001:
        print("Anomalo")
    elif prob >= 0.000000000000000000000000000000000000000000001:
        print("No Anomalo")

In [69]:
clasificacion_p(1,34)

Anomalo


# Area de pruebas 

In [85]:
## pdf de la edad
uno = norm.pdf(x_anomalias[:,0],medias[0],varianza[0])

In [86]:
uno

array([0., 0., 0., 0.])

In [87]:
## pdf de la estatura
dos = norm.pdf(x_anomalias[:,1],medias[1],varianza[1])

In [88]:
dos

array([9.34349263e-03, 9.39079450e-03, 8.80944594e-24, 1.47000028e-02])

In [89]:
tres = uno**dos

In [90]:
tres

array([0., 0., 0., 0.])

In [36]:
cuatro = tres < 0.1

In [37]:
cuatro

array([ True,  True,  True,  True])

In [37]:
norm.pdf(0)

0.3989422804014327

Caracteristicas que pueden ser un indicativo para que algo sea anomalo

In [ ]:
x_train = np.array ([[140,16],
                     [170,45],
                     [165,49],
                     [159,64],
                     [149,25],
                     [165,39],
                     [170,45],
                     [165,49],
                     [159,64],
                     [149,25],
                     [165,39],
                     [170,45],
                     [165,49],
                     [159,64],
                     [149,25],
                     [165,39],
                     [170,45],
                     [165,49],
                     [159,64],
                     [144,70],])