# Johnatan Meoño

In [1]:
from sklearn.preprocessing import PolynomialFeatures

In [2]:
import numpy as np

In [3]:
import pandas as pd

# Una variable 

In [4]:
x1 = np.random.rand(5,1)
x1

array([[0.11742726],
       [0.97124859],
       [0.63327312],
       [0.50810265],
       [0.75619945]])

In [5]:
poly1 = PolynomialFeatures(3)
pd.DataFrame(poly1.fit_transform(x1))

0         1         2         3
0  1.0  0.117427  0.013789  0.001619
1  1.0  0.971249  0.943324  0.916202
2  1.0  0.633273  0.401035  0.253965
3  1.0  0.508103  0.258168  0.131176
4  1.0  0.756199  0.571838  0.432423

# Dos variables

In [6]:
x2 = np.random.rand(5,2)
x2

array([[0.65262835, 0.86004552],
       [0.65718927, 0.18059617],
       [0.60104082, 0.51306622],
       [0.27942709, 0.74971068],
       [0.01397174, 0.88872061]])

In [7]:
poly2 = PolynomialFeatures(3)
pd.DataFrame(poly2.fit_transform(x2))

0         1         2         3         4         5         6         7  \
0  1.0  0.652628  0.860046  0.425924  0.561290  0.739678  0.277970  0.366314   
1  1.0  0.657189  0.180596  0.431898  0.118686  0.032615  0.283839  0.077999   
2  1.0  0.601041  0.513066  0.361250  0.308374  0.263237  0.217126  0.185345   
3  1.0  0.279427  0.749711  0.078079  0.209489  0.562066  0.021818  0.058537   
4  1.0  0.013972  0.888721  0.000195  0.012417  0.789824  0.000003  0.000173   

          8         9  
0  0.482735  0.636157  
1  0.021434  0.005890  
2  0.158216  0.135058  
3  0.157056  0.421387  
4  0.011035  0.701933

# Tres variables

In [8]:
x3 = np.random.rand(5,3)
x3

array([[0.85103776, 0.68077173, 0.13038352],
       [0.21578885, 0.04541435, 0.40321869],
       [0.27357724, 0.90951906, 0.42619025],
       [0.43418068, 0.75538188, 0.25699589],
       [0.80402888, 0.80340734, 0.0589459 ]])

In [9]:
poly3 = PolynomialFeatures(3)
pd.DataFrame(poly3.fit_transform(x3))

0         1         2         3         4         5         6         7   \
0  1.0  0.851038  0.680772  0.130384  0.724265  0.579362  0.110961  0.463450   
1  1.0  0.215789  0.045414  0.403219  0.046565  0.009800  0.087010  0.002062   
2  1.0  0.273577  0.909519  0.426190  0.074845  0.248824  0.116596  0.827225   
3  1.0  0.434181  0.755382  0.256996  0.188513  0.327972  0.111583  0.570602   
4  1.0  0.804029  0.803407  0.058946  0.646462  0.645963  0.047394  0.645463   

         8         9         10        11        12        13        14  \
0  0.088761  0.017000  0.616377  0.493059  0.094432  0.394414  0.075539   
1  0.018312  0.162585  0.010048  0.002115  0.018776  0.000445  0.003952   
2  0.387628  0.181638  0.020476  0.068073  0.031898  0.226310  0.106046   
3  0.194130  0.066047  0.081849  0.142399  0.048447  0.247744  0.084288   
4  0.047358  0.003475  0.519774  0.519373  0.038106  0.518971  0.038077   

         15        16        17        18        19  
0  0.014468  0.315504  0.060426  0.011573  0.002217  
1  0.035084  0.000094  0.000832  0.007384  0.065557  
2  0.049692  0.752377  0.352555  0.165203  0.077412  
3  0.028676  0.431022  0.146642  0.049891  0.016974  
4  0.002794  0.518570  0.038047  0.002792  0.000205

# Conclusión

### Entre más features poseamos antes de generar un polinomio, mas features tendremos luego de generar un nuevo polinomio. Como es sabido la maldición de la dimensionalidad significa que el número de objetos en el conjunto de datos a los que se necesita acceder crece exponencialmente con la dimensionalidad subyacente.

In [10]:
print('Combinando 1 variable:',np.shape(pd.DataFrame(poly1.fit_transform(x1)))[1])
print('Combinando 2 variables:',np.shape(pd.DataFrame(poly2.fit_transform(x2)))[1])
print('Combinando 2 variables:',np.shape(pd.DataFrame(poly3.fit_transform(x3)))[1])

Combinando 1 variable: 4
Combinando 2 variables: 10
Combinando 2 variables: 20
